title = "jsstrn > notes"
theme = "anubis"
baseUrl = "https://notes.jsstrn.me/"
paginate = 5
languageCode = "en-us"
publishDir = "docs"

[params]
  author = "Jesstern Rays"
  description = "Jesstern's notes"
  dateFormat = "2006-01-02"
  paginationSinglePost = true
  style = "dark-without-switcher"
  readMore = false

[menu]

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 1

  [[menu.main]]
    name = "categories"
    identifier = "categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about/"
    weight = 3


[taxonomies]
  category = "categories"
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true
